---
- name: Install certbot-dns-cloudflare plugin
  ansible.builtin.include_role:
    name: geerlingguy.pip
    vars:
      pip_install_packages:
        - name: certbot-dns-cloudflare

- name: Certbot template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - src: "templates/dns-cloudflare.ini.j2"
      dest: "/etc/letsencrypt/dns-cloudflare.ini"
    - src: "templates/certbot-cli.ini.j2"
      dest: "/etc/letsencrypt/cli.ini"

- name: Create certs
  ansible.builtin.include_role:
    name: geerlingguy.certbot
