---
# tasks file for certbot-cloudflare

- name: Get software for APT repository management
  ansible.builtin.apt: name={{ item }} state=present
  with_items:
    - build-essential
    - curl
    - libffi-dev
    - libssl-dev
    - python-apt
    - python-dev
    - python-pycurl

- name: Check if certbot-dns-cloudflare plugin is installed
  ansible.builtin.shell: certbot plugins | grep dns-cloudflare
  register: cf_check
  ignore_errors: true
  changed_when: "cf_check is failed"

- name: Install certbot-dns-cloudflare
  ansible.builtin.shell: "cd {{ certbot_dir }}/certbot-dns-cloudflare && python setup.py install"
  when: "cf_check is failed"

- name: Create Certbot folder - sudouser
  ansible.builtin.file:
    path: /etc/letsencrypt
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Certbot template
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - src: "templates/confcloudflare.ini.j2"
      dest: "/etc/letsencrypt/dnscloudflare.ini"
    - src: "templates/letsencrypt_cli.ini.j2"
      dest: "/etc/letsencrypt/cli.ini"

- name: Create certs
  ansible.builtin.include_role:
    name: geerlingguy.certbot
